# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIssuer',
            fields=[
                ('descriptor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payments_card_issuer',
                'verbose_name_plural': 'Card Issuers',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('name', models.CharField(choices=[('PP', 'PayPal'), ('ST', 'Stripe'), ('AP', 'Amazon Payments')], help_text='Payment processing gateway.', max_length=10, primary_key=True, serialize=False)),
                ('account', models.CharField(help_text='Account name of gateway for reference.', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Gateway active for customer to buy through it.')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Sandbox mode for testing & debugging.')),
                ('accept_credit_card', models.BooleanField(default=False, help_text='Process credit card payments.')),
                ('accept_account', models.BooleanField(default=False, help_text="Process payments with customer's existing accounts on gateway, like PayPal account.")),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gateway settings parameter name.', max_length=250)),
                ('value', models.CharField(help_text='Gateway settings parameter value.', max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='payments.Gateway')),
            ],
            options={
                'db_table': 'payments_gateway_param',
                'verbose_name_plural': 'Gateway Params',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('error_message', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('AP', 'Approved'), ('FA', 'Failed'), ('RE', 'Refunded')], max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Gateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Transaction parameter name.', max_length=100)),
                ('value', models.CharField(help_text='Transaction parameter value.', max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='payments.Transaction')),
            ],
            options={
                'db_table': 'payments_transaction_param',
                'verbose_name_plural': 'Transaction Params',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transactionparam',
            unique_together=set([('transaction', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='gatewayparam',
            unique_together=set([('gateway', 'name')]),
        ),
    ]
