# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(help_text='Group text under which links will be compiled for display.', max_length=100)),
                ('url', models.CharField(blank=True, help_text='Url of resource this link points to.', max_length=500, null=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Title text to be used in url for this post', max_length=255, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('WD', 'Withdrawn'), ('PU', 'Published')], default='DR', max_length=2)),
                ('tags', models.CharField(blank=True, help_text='Tags for the published article', max_length=255, null=True)),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='published date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('created_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('updated_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Page resource this link points to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
