# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-08 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verify_code', models.CharField(blank=True, editable=False, help_text='User account verification code.', max_length=512, null=True)),
                ('reset_code', models.CharField(blank=True, editable=False, help_text='Password reset code.', max_length=512, null=True)),
                ('reset_code_expire', models.DateTimeField(blank=True, editable=False, help_text='Password reset code expire date.', max_length=512, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
