# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
