# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='id_interno',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=256, verbose_name='Direcci\xf3n Referencia'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='id_ministerio',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Identificador Ministerior'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='razon_social',
            field=models.CharField(max_length=256, unique=True, verbose_name='Raz\xf3n Social'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC/CI'),
        ),
    ]
