# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180112_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='id_ministerio',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Identificador Ministerior'),
        ),
    ]
