# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20180112_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('user__username',)},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='name',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
