# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('catalog', '0005_auto_20180112_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.Country'),
            preserve_default=False,
        ),
    ]
