# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20180116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_or_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
