# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('BK', 'Bank Deposit')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
